// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sample.Data;

#nullable disable

namespace Sample.Data.Migrations.TenantDb
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260120083923_isActiveColAdded")]
    partial class isActiveColAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sample.Data.RoutingDB.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfirmPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Sample.Data.RoutingDB.tblClientDetails", b =>
                {
                    b.Property<int>("client_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("client_id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ApprovalSystem")
                        .HasColumnType("bit");

                    b.Property<bool>("CID")
                        .HasColumnType("bit");

                    b.Property<bool>("CollectionApp")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Primary_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Primary_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SMS_service")
                        .HasColumnType("bit");

                    b.Property<string>("Secondary_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Secondary_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("client_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("created_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("db_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("db_pwd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("db_username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<int>("modified_by")
                        .HasColumnType("int");

                    b.Property<DateTime>("modified_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("server_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("client_id");

                    b.ToTable("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
